@echo off
echo Killing stuck java/gradle...
taskkill /F /IM java.exe /T >NUL 2>&1
call gradlew --stop
echo Removing build\...
rmdir /S /Q build 2>NUL
set "JAVA_HOME=C:\Program Files\Eclipse Adoptium\jdk-21.0.8.9-hotspot"
set "PATH=%JAVA_HOME%\bin;%PATH%"
echo Rebuilding sources...
call gradlew clean compileJava
echo Launching dev client...
call gradlew runClient
